# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-24 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vessel_planner', '0003_auto_20190119_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselprogress',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipping_line.VesselArrival'),
        ),
    ]
