# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-29 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vessel_planner', '0005_auto_20190127_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselprogress',
            name='vessel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipping_line.VesselArrival'),
        ),
    ]
