# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-29 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vessel_planner', '0006_auto_20190129_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='message_author',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
