# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berth_planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BerthAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berth_planner.Berth')),
            ],
        ),
    ]
