# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-30 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth_planner', '0002_berthallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='berth',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
