# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-30 23:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth_planner', '0003_berth_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berthallocation',
            name='berth',
        ),
        migrations.AddField(
            model_name='berthallocation',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berthallocation',
            name='schedule_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berthallocation',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
