# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-30 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth_planner', '0004_auto_20190130_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berthallocation',
            name='end_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='berthallocation',
            name='start_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
