# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180823_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingagent',
            name='is_active_agent',
            field=models.BooleanField(default=False),
        ),
    ]
