# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shippingagent_shipping_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(blank=True, choices=[('BP', 'Berth Planner'), ('SA', 'Shipping Agent'), ('ADMIN', 'System Admin')], max_length=10, null=True),
        ),
    ]
