# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-09 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180905_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berthplanner',
            name='account',
        ),
        migrations.DeleteModel(
            name='BerthPlanner',
        ),
    ]
