# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-02 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_line', '0002_vesseldetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vesseldetails',
            options={'ordering': ['eta'], 'verbose_name': 'Vessel Details', 'verbose_name_plural': 'Vessel Details'},
        ),
    ]
