# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_line', '0003_auto_20180902_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vesseldetails',
            name='etb',
        ),
        migrations.RemoveField(
            model_name='vesseldetails',
            name='etc',
        ),
        migrations.RemoveField(
            model_name='vesseldetails',
            name='is_at_berth',
        ),
        migrations.AddField(
            model_name='vesseldetails',
            name='last_port',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vesseldetails',
            name='next_port',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vesseldetails',
            name='service',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vesseldetails',
            name='loa_val',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
