# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_line', '0004_auto_20180905_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesseldetails',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
