# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-09 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_line', '0005_auto_20180907_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vessel',
            old_name='loa_val',
            new_name='_loa',
        ),
        migrations.RemoveField(
            model_name='vesseldetails',
            name='total',
        ),
    ]
