# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-09 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_line', '0006_auto_20180909_0650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VesselDetails',
            new_name='VesselArrival',
        ),
    ]
