# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_line', '0007_auto_20180909_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselarrival',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vesselarrival',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
