# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-12 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_line', '0010_auto_20180911_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingline',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vessel_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='vesselarrival',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shipping_line.Vessel'),
        ),
    ]
