# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-05 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_line', '0011_auto_20180912_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselarrival',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vessel', to='shipping_line.Vessel'),
        ),
    ]
