# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-24 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_line', '0012_auto_20181205_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselarrival',
            name='eta',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vesselarrival',
            name='ref_no',
            field=models.CharField(max_length=100),
        ),
    ]
