# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-27 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_line', '0013_auto_20190124_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselarrival',
            name='ref_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
