# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-27 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190124_1358'),
        ('shipping_line', '0014_auto_20190127_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.ShippingAgent'),
        ),
    ]
