# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-30 07:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_line', '0016_auto_20190130_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselarrival',
            name='schedule_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
