# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-30 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_line', '0017_vesselarrival_schedule_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselarrival',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
